### ISSUE TITLE
Checkout showing incorrect date

### ISSUE THREAD

**Issue by mintplugins** [RebelCode/edd-bookings#29]
Using FES and Bookings 2.2.4 with a Vendor-created product, I have added a time to the cart but it is showing `December 31, 2969` as the chosen time - which is not the time I am trying to purchase. 

<img width="753" alt="screen shot 2017-07-13 at 10 10 36 am" src="https://user-images.githubusercontent.com/1638128/28170560-cbf29656-67b3-11e7-89b7-6064aade6767.png">

Screenshot of configuration:
<img width="948" alt="screen shot 2017-07-13 at 10 12 55 am" src="https://user-images.githubusercontent.com/1638128/28170594-e35d31b6-67b3-11e7-9541-f24bff4f5202.png">

**Comment by mecha** [comment]
Cause of this bug is related to #30. Fixed in [v2.2.4](https://github.com/RebelCode/edd-bookings/releases/tag/v2.2.4).
