### ISSUE TITLE
Plugin won't activate if phpxml is not installed. 

### ISSUE THREAD

**Issue by mintplugins** [RebelCode/edd-bookings#31]
If your server does not have `libxml` installed, you can't activate EDD Bookings. Digital Ocean does not include this by default with PHP. 

Instead of throwing a fatal error upon installation, this should be detected and give the user a meaningful error message letting them know how to proceed.

**Comment by mintplugins** [comment]
Installing `libxml` actually made no difference. What I did need was `phpxml`.

**Comment by mintplugins** [comment]
@markzahra

**Comment by mecha** [comment]
Agreed. There needs to be a check for this with appropriate handling and output to the user.
