### ISSUE TITLE
Untranslate-able strings

### ISSUE THREAD

**Issue by mintplugins** [RebelCode/edd-bookings#32]
There are  few untranslate-able strings that a customer is complaining about as they are trying to translate their site into Swedish. 

Here are a few that I've found in a quick search:

https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L31
https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L55
https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L72
https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L90
https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L108
https://github.com/RebelCode/edd-bookings/blob/develop/views/Admin/Bookings/Info.php#L137

There may be more still. If you guys could go through and check for all strings that are not wrapped in WordPress translation functions that would be great.

**Comment by markzahra** [comment]
@mintplugins we're looking into it, we'll keep you updated.

**Comment by mecha** [comment]
Went through the plugin and translated everything except for a few which are known to be problematic:

- `moment.js` "Invalid date" message: depends on the language(for instance Italian does not translate it)
- Changelog on the About page
- First 4 settings in the FES field (these are translated by FES).
